"use client";

import { useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Download, Send } from "lucide-react";
import { toast } from "sonner";

import { sendReportToClient } from "@/app/actions/reports";
import { GenerateReportButton } from "@/components/reports/generate-report-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { formatDate } from "@/lib/format";
import type { DemoReportRecord } from "@/lib/demo/types";

function formatSize(bytes: number): string {
  return `${Math.max(Math.round(bytes / 1024), 1)} KB`;
}

type ClientReportsPanelProps = {
  clientId: string;
  reports: DemoReportRecord[];
  canGenerate: boolean;
};

export function ClientReportsPanel({
  clientId,
  reports,
  canGenerate,
}: ClientReportsPanelProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  function send(reportId: string) {
    startTransition(async () => {
      const result = await sendReportToClient(reportId);

      if (!result.ok) {
        toast.error(result.message ?? "Could not send the report.");
        return;
      }

      toast.success("Report sent to the client. It appears under Documents.");
      router.refresh();
    });
  }

  return (
    <Card className="shadow-none">
      <CardHeader>
        <CardTitle>Reports</CardTitle>
        <CardDescription>
          Branded PDFs generated from this client&apos;s live portfolio data.
        </CardDescription>
        {canGenerate ? (
          <CardAction>
            <GenerateReportButton clientId={clientId} />
          </CardAction>
        ) : null}
      </CardHeader>
      <CardContent className="space-y-2">
        {reports.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No reports generated yet.
          </p>
        ) : (
          reports.map((report) => (
            <div
              key={report.id}
              className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"
            >
              <div className="min-w-0 space-y-0.5">
                <p className="flex flex-wrap items-center gap-2 text-sm font-medium">
                  {report.title}
                  {report.sentAt ? (
                    <Badge variant="secondary">Sent</Badge>
                  ) : (
                    <Badge variant="outline">Internal</Badge>
                  )}
                </p>
                <p className="text-xs text-muted-foreground">
                  {report.periodLabel} · {formatSize(report.sizeBytes)} ·
                  generated by {report.generatedByName} on{" "}
                  {formatDate(report.createdAt)}
                </p>
              </div>

              <div className="flex shrink-0 items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  render={
                    <Link
                      href={`/api/reports/${encodeURIComponent(report.id)}/download`}
                      target="_blank"
                      rel="noreferrer"
                    />
                  }
                >
                  <Download />
                  Open
                </Button>
                {canGenerate && !report.sentAt ? (
                  <Button
                    size="sm"
                    disabled={isPending}
                    onClick={() => send(report.id)}
                  >
                    <Send />
                    Send
                  </Button>
                ) : null}
              </div>
            </div>
          ))
        )}
      </CardContent>
    </Card>
  );
}
