import {
  defaultAssetMandate,
  type AssetMandate,
} from "@/lib/demo/seed/asset-mandate";
import {
  buildClientRecord,
  type ClientSpec,
} from "@/lib/demo/seed/client-builder";
import { enrichClientSpec } from "@/lib/demo/seed/enrich-client-spec";
import { ADA_MENSAH_SPEC } from "@/lib/demo/seed/reference-persona";
import {
  AGGRESSIVE_SLEEVES,
  BALANCED_SLEEVES,
  expensesFor,
  GROWTH_SLEEVES,
  holdingsFrom,
  INCOME_SLEEVES,
  incomeFor,
} from "@/lib/demo/seed/portfolio-helpers";
import { REGIONAL_CLIENT_SPECS } from "@/lib/demo/seed/regional-clients";
import { resolveFillerResidency } from "@/lib/demo/seed/residency-locations";
import type { DemoClientRecord } from "@/lib/demo/types";

const SPECS: ClientSpec[] = [
  ADA_MENSAH_SPEC,
  {
    id: "osei-bonsu",
    firstName: "Akosua",
    lastName: "Osei-Bonsu",
    email: "akosua.osei-bonsu@example.com",
    phone: "+44 20 7946 1122",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "ultra",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "London / Accra",
    city: "London",
    country: "United Kingdom",
    residency: "UK resident, GH domicile",
    occupation: "Founder, industrial group",
    maritalStatus: "married",
    gender: "female",
    age: 58,
    citizenships: ["GH", "GB"],
    joinedDaysAgo: 3650,
    lastContactDaysAgo: 9,
    nextReviewInDays: 21,
    bio: "Second-generation industrialist consolidating cross-border wealth ahead of a partial business exit.",
    notes:
      "Cash weighting has drifted well above mandate after the Q2 dividend. Education goal for 2027 is behind plan.",
    holdings: [
      ...holdingsFrom(36_256_000, GROWTH_SLEEVES),
      {
        name: "Fidelity US Equity Sleeve",
        symbol: "FUSE",
        assetType: "Equities",
        value: 2_400_000,
        costBasis: 1_950_000,
        relationship: "aua" as const,
      },
    ],
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 3_244_000 },
      { name: "USD Call Deposit", institution: "Fidelity Bank", type: "deposit", balance: 1_700_000 },
    ],
    goals: [
      { title: "UK tuition fund", category: "Education", target: 1_800_000, current: 1_278_000, monthly: 14_500, years: 2, priority: 1 },
      { title: "Family office seed", category: "Legacy", target: 12_000_000, current: 7_400_000, monthly: 60_000, years: 6, priority: 2 },
      { title: "Accra campus endowment", category: "Philanthropy", target: 5_000_000, current: 2_150_000, monthly: 22_000, years: 8, priority: 3 },
    ],
    properties: [
      { name: "Kensington townhouse", type: "residential", country: "United Kingdom", city: "London", purchase: 6_100_000, current: 8_450_000 },
      { name: "Airport Residential villa", type: "residential", country: "Ghana", city: "Accra", purchase: 1_900_000, current: 2_600_000 },
    ],
    liabilities: [
      { name: "Kensington mortgage", lender: "Fidelity Bank", type: "mortgage", balance: 2_300_000, ratePct: 5.1, monthly: 18_400 },
    ],
    insurance: [
      { category: "life", provider: "Aegis Global", name: "Whole of life cover", coverage: 10_000_000, premium: 7_200 },
      { category: "health", provider: "Bupa", name: "International health", coverage: 2_000_000, premium: 3_100 },
    ],
    income: incomeFor(196_000),
    expenses: expensesFor(88_000),
    dependents: [
      { name: "Nana Osei-Bonsu", relationship: "daughter", ageYears: 17 },
      { name: "Kojo Osei-Bonsu", relationship: "son", ageYears: 14 },
    ],
    targetCashPct: 4,
    assetMandate: "mixed",
    heldAwayUsd: 10_150_000,
    portfolioDriftPct: 5.4,
    revenueQtdUsd: 286_000,
    netFlowQtdUsd: 2_400_000,
    performanceYtdPct: 9.2,
    retirementAge: 64,
    desiredMonthlyIncome: 95_000,
    maturingInvestment: null,
    effectiveTaxRatePct: 31,
    marginalTaxRatePct: 45,
  },
  {
    id: "darko",
    firstName: "Yaw",
    lastName: "Darko",
    email: "yaw.darko@example.com",
    phone: "+233 30 274 9010",
    status: "review",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Chief Executive, logistics",
    maritalStatus: "married",
    gender: "male",
    age: 51,
    citizenships: ["GH"],
    joinedDaysAgo: 1580,
    lastContactDaysAgo: 4,
    nextReviewInDays: 6,
    bio: "Operating executive with concentrated equity exposure from a recent secondary sale.",
    notes:
      "Portfolio has drifted outside the moderate risk band. Needs a documented rebalance before the next review.",
    holdings: holdingsFrom(14_900_000, AGGRESSIVE_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 620_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 9_000_000, current: 5_600_000, monthly: 26_000, years: 12, priority: 1 },
      { title: "Second home", category: "Property", target: 2_200_000, current: 900_000, monthly: 12_000, years: 4, priority: 2 },
    ],
    properties: [
      { name: "Cantonments residence", type: "residential", country: "Ghana", city: "Accra", purchase: 1_400_000, current: 1_950_000 },
    ],
    liabilities: [
      { name: "Business facility", lender: "Fidelity Bank", type: "commercial", balance: 1_100_000, ratePct: 9.4, monthly: 21_000 },
    ],
    insurance: [
      { category: "life", provider: "Enterprise Life", name: "Term cover", coverage: 4_000_000, premium: 1_900 },
    ],
    income: incomeFor(84_000),
    expenses: expensesFor(41_000),
    dependents: [{ name: "Afia Darko", relationship: "daughter", ageYears: 12 }],
    targetCashPct: 5,
    assetMandate: "mixed",
    heldAwayUsd: 1_200_000,
    portfolioDriftPct: 11.6,
    revenueQtdUsd: 104_000,
    netFlowQtdUsd: -350_000,
    performanceYtdPct: 12.4,
    maturingInvestment: null,
  },
  {
    id: "quaye",
    firstName: "Mabel",
    lastName: "Quaye",
    email: "mabel.quaye@example.com",
    phone: "+233 30 291 4477",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Managing Partner, healthcare",
    maritalStatus: "single",
    gender: "female",
    age: 46,
    citizenships: ["GH", "US"],
    joinedDaysAgo: 940,
    lastContactDaysAgo: 2,
    nextReviewInDays: 34,
    bio: "Clinic group founder holding proceeds in cash after a partial stake sale.",
    notes:
      "Sale proceeds landed three weeks ago and are ready to fund. Deployment plan agreed in principle.",
    holdings: holdingsFrom(8_600_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 2_950_000 },
    ],
    goals: [
      { title: "Clinic expansion reserve", category: "Business", target: 4_000_000, current: 2_600_000, monthly: 30_000, years: 3, priority: 1 },
      { title: "Retirement income", category: "Retirement", target: 7_000_000, current: 3_100_000, monthly: 20_000, years: 16, priority: 2 },
    ],
    properties: [],
    liabilities: [],
    insurance: [
      { category: "health", provider: "Bupa", name: "International health", coverage: 1_500_000, premium: 2_400 },
    ],
    income: incomeFor(72_000),
    expenses: expensesFor(29_000),
    dependents: [],
    targetCashPct: 5,
    heldAwayUsd: 0,
    portfolioDriftPct: 3.1,
    revenueQtdUsd: 71_000,
    netFlowQtdUsd: 2_950_000,
    performanceYtdPct: 8.4,
    maturingInvestment: null,
  },
  {
    id: "mensah-kofi",
    firstName: "Kofi",
    lastName: "Mensah",
    email: "kofi.mensah@example.com",
    phone: "+233 30 288 3321",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Kumasi, Ghana",
    city: "Kumasi",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Retired executive",
    maritalStatus: "married",
    gender: "male",
    age: 67,
    citizenships: ["GH"],
    joinedDaysAgo: 2450,
    lastContactDaysAgo: 15,
    nextReviewInDays: 12,
    bio: "Retired and drawing a steady income from a laddered fixed income portfolio.",
    notes:
      "A $1.4m note matures shortly. Reinvestment decision needed to avoid a cash drag.",
    holdings: holdingsFrom(11_200_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 480_000 },
    ],
    goals: [
      { title: "Lifetime income", category: "Retirement", target: 12_000_000, current: 11_100_000, monthly: 0, years: 1, priority: 1 },
      { title: "Grandchildren education", category: "Education", target: 900_000, current: 610_000, monthly: 4_500, years: 7, priority: 2 },
    ],
    properties: [
      { name: "Ridge family home", type: "residential", country: "Ghana", city: "Kumasi", purchase: 620_000, current: 880_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Enterprise Life", name: "Whole of life cover", coverage: 2_000_000, premium: 2_800 },
    ],
    income: incomeFor(48_000),
    expenses: expensesFor(26_000),
    dependents: [],
    targetCashPct: 6,
    heldAwayUsd: 350_000,
    portfolioDriftPct: 2.2,
    revenueQtdUsd: 58_000,
    netFlowQtdUsd: 120_000,
    performanceYtdPct: 5.1,
    maturingInvestment: {
      name: "5.4% Sovereign Note 2026",
      valueUsd: 1_400_000,
      maturesInDays: 5,
    },
  },
  {
    id: "asare",
    firstName: "Efua",
    lastName: "Asare",
    email: "efua.asare@example.com",
    phone: "+233 30 265 7788",
    status: "review",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Ho, Ghana",
    city: "Ho",
    country: "Ghana",
    regionCode: "TV",
    residency: "GH resident",
    occupation: "Partner, corporate law",
    maritalStatus: "married",
    gender: "female",
    age: 49,
    citizenships: ["GH"],
    joinedDaysAgo: 1290,
    lastContactDaysAgo: 63,
    nextReviewInDays: -18,
    bio: "Law firm partner with a straightforward balanced mandate.",
    notes: "Annual review is overdue. Two attempts to schedule have lapsed.",
    holdings: holdingsFrom(9_400_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 700_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 8_000_000, current: 4_700_000, monthly: 22_000, years: 14, priority: 1 },
    ],
    properties: [],
    liabilities: [
      { name: "Residential mortgage", lender: "Fidelity Bank", type: "mortgage", balance: 540_000, ratePct: 8.2, monthly: 6_900 },
    ],
    insurance: [],
    income: incomeFor(62_000),
    expenses: expensesFor(33_000),
    dependents: [{ name: "Kwabena Asare", relationship: "son", ageYears: 9 }],
    targetCashPct: 5,
    heldAwayUsd: 0,
    portfolioDriftPct: 4.4,
    revenueQtdUsd: 47_000,
    netFlowQtdUsd: 0,
    performanceYtdPct: 6.8,
    maturingInvestment: null,
  },
  {
    id: "adjei",
    firstName: "Nii",
    lastName: "Adjei",
    email: "nii.adjei@example.com",
    phone: "+233 30 233 1290",
    status: "review",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Tema, Ghana",
    city: "Tema",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Shipping executive",
    maritalStatus: "married",
    gender: "male",
    age: 44,
    citizenships: ["GH"],
    joinedDaysAgo: 810,
    lastContactDaysAgo: 71,
    nextReviewInDays: -9,
    bio: "Mid-career executive building long-horizon growth exposure.",
    notes: "Review overdue. Client has asked for a written portfolio commentary.",
    holdings: holdingsFrom(4_300_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 260_000 },
    ],
    goals: [
      { title: "Children education", category: "Education", target: 1_100_000, current: 420_000, monthly: 9_000, years: 9, priority: 1 },
      { title: "Retirement income", category: "Retirement", target: 5_000_000, current: 2_100_000, monthly: 15_000, years: 21, priority: 2 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(38_000),
    expenses: expensesFor(22_000),
    dependents: [
      { name: "Adjoa Adjei", relationship: "daughter", ageYears: 8 },
      { name: "Kojo Adjei", relationship: "son", ageYears: 5 },
    ],
    targetCashPct: 5,
    heldAwayUsd: 0,
    portfolioDriftPct: 6.1,
    revenueQtdUsd: 24_000,
    netFlowQtdUsd: 60_000,
    performanceYtdPct: 10.1,
    maturingInvestment: null,
  },
  {
    id: "nkrumah",
    firstName: "Abena",
    lastName: "Nkrumah",
    email: "abena.nkrumah@example.com",
    phone: "+233 30 279 6654",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Non-executive director",
    maritalStatus: "widowed",
    gender: "female",
    age: 63,
    citizenships: ["GH"],
    joinedDaysAgo: 1980,
    lastContactDaysAgo: 6,
    nextReviewInDays: 40,
    bio: "Conservative mandate with a strict capital preservation objective.",
    notes:
      "Escalation open: client disputes the structured note allocation recommended last quarter.",
    holdings: holdingsFrom(13_700_000, AGGRESSIVE_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 910_000 },
    ],
    goals: [
      { title: "Capital preservation", category: "Wealth", target: 15_000_000, current: 14_600_000, monthly: 0, years: 5, priority: 1 },
    ],
    properties: [
      { name: "Labone apartment", type: "residential", country: "Ghana", city: "Accra", purchase: 780_000, current: 1_050_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "health", provider: "Bupa", name: "International health", coverage: 1_200_000, premium: 3_600 },
    ],
    income: incomeFor(44_000),
    expenses: expensesFor(24_000),
    dependents: [],
    targetCashPct: 8,
    heldAwayUsd: 0,
    portfolioDriftPct: 14.2,
    revenueQtdUsd: 82_000,
    netFlowQtdUsd: -180_000,
    performanceYtdPct: 11.8,
    maturingInvestment: null,
  },
  {
    id: "owusu-ansah",
    firstName: "Kwabena",
    lastName: "Owusu-Ansah",
    email: "kwabena.owusu-ansah@example.com",
    phone: "+233 30 244 8812",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "ultra",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra / Dubai",
    city: "Accra",
    country: "Ghana",
    residency: "GH resident, AE tax resident",
    occupation: "Real estate developer",
    maritalStatus: "married",
    gender: "male",
    age: 54,
    citizenships: ["GH"],
    joinedDaysAgo: 2760,
    lastContactDaysAgo: 11,
    nextReviewInDays: 27,
    bio: "Developer with a large illiquid property book seeking liquidity without asset sales.",
    notes:
      "Strong candidate for a Lombard facility against the marketable securities portfolio.",
    holdings: holdingsFrom(23_800_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 1_150_000 },
    ],
    goals: [
      { title: "Development capital", category: "Business", target: 15_000_000, current: 6_900_000, monthly: 85_000, years: 4, priority: 1 },
      { title: "Family legacy", category: "Legacy", target: 20_000_000, current: 12_400_000, monthly: 40_000, years: 10, priority: 2 },
    ],
    properties: [
      { name: "Airport City tower", type: "commercial", country: "Ghana", city: "Accra", purchase: 14_000_000, current: 19_800_000 },
      { name: "Dubai Marina apartment", type: "residential", country: "United Arab Emirates", city: "Dubai", purchase: 2_100_000, current: 3_050_000 },
    ],
    liabilities: [
      { name: "Development loan", lender: "Fidelity Bank", type: "commercial", balance: 6_400_000, ratePct: 8.9, monthly: 78_000 },
    ],
    insurance: [
      { category: "life", provider: "Aegis Global", name: "Key person cover", coverage: 8_000_000, premium: 6_100 },
    ],
    income: incomeFor(158_000),
    expenses: expensesFor(74_000),
    dependents: [{ name: "Maame Owusu-Ansah", relationship: "daughter", ageYears: 19 }],
    targetCashPct: 4,
    heldAwayUsd: 4_600_000,
    portfolioDriftPct: 3.8,
    revenueQtdUsd: 214_000,
    netFlowQtdUsd: 900_000,
    performanceYtdPct: 8.9,
    maturingInvestment: null,
  },
  {
    id: "tetteh",
    firstName: "Naa",
    lastName: "Tetteh",
    email: "naa.tetteh@example.com",
    phone: "+233 30 222 5540",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "GBP",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Manchester, UK",
    city: "Manchester",
    country: "United Kingdom",
    residency: "UK resident",
    occupation: "Consultant physician",
    maritalStatus: "married",
    gender: "female",
    age: 47,
    citizenships: ["GB", "GH"],
    joinedDaysAgo: 1120,
    lastContactDaysAgo: 19,
    nextReviewInDays: 45,
    bio: "Consultant with substantial pension assets held outside the bank.",
    notes:
      "NHS pension and two ISAs sit away from the bank. Consolidation conversation is warranted.",
    holdings: holdingsFrom(6_800_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 340_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 7_500_000, current: 4_200_000, monthly: 18_000, years: 15, priority: 1 },
      { title: "Property purchase", category: "Property", target: 1_400_000, current: 520_000, monthly: 8_000, years: 5, priority: 2 },
    ],
    properties: [
      { name: "Didsbury home", type: "residential", country: "United Kingdom", city: "Manchester", purchase: 1_250_000, current: 1_620_000 },
    ],
    liabilities: [
      { name: "Residential mortgage", lender: "Third party", type: "mortgage", balance: 460_000, ratePct: 4.7, monthly: 3_900 },
    ],
    insurance: [
      { category: "life", provider: "Aviva", name: "Level term cover", coverage: 2_500_000, premium: 1_400 },
    ],
    income: incomeFor(46_000),
    expenses: expensesFor(27_000),
    dependents: [{ name: "Kofi Tetteh", relationship: "son", ageYears: 11 }],
    targetCashPct: 5,
    heldAwayUsd: 5_400_000,
    portfolioDriftPct: 2.9,
    revenueQtdUsd: 38_000,
    netFlowQtdUsd: 150_000,
    performanceYtdPct: 7.2,
    maturingInvestment: null,
  },
  {
    id: "agyapong",
    firstName: "Selina",
    lastName: "Agyapong",
    email: "selina.agyapong@example.com",
    phone: "+233 30 211 7734",
    status: "onboarding",
    riskLevel: "moderate",
    subscription: "free_trial",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Technology founder",
    maritalStatus: "single",
    gender: "female",
    age: 38,
    citizenships: ["GH"],
    joinedDaysAgo: 24,
    lastContactDaysAgo: 3,
    nextReviewInDays: 14,
    bio: "New relationship onboarding after a Series B secondary.",
    notes: "KYC documents outstanding. Risk profile complete, funding pending.",
    holdings: holdingsFrom(1_900_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 640_000 },
    ],
    goals: [
      { title: "Diversify founder stock", category: "Wealth", target: 5_000_000, current: 1_900_000, monthly: 25_000, years: 6, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(34_000),
    expenses: expensesFor(17_000),
    dependents: [],
    targetCashPct: 6,
    heldAwayUsd: 2_100_000,
    portfolioDriftPct: 1.4,
    revenueQtdUsd: 9_000,
    netFlowQtdUsd: 640_000,
    performanceYtdPct: 4.2,
    maturingInvestment: null,
  },
  {
    id: "boadu",
    firstName: "Yaa",
    lastName: "Boadu",
    email: "yaa.boadu@example.com",
    phone: "+233 30 256 9902",
    status: "inactive",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Takoradi, Ghana",
    city: "Takoradi",
    country: "Ghana",
    residency: "GH resident",
    occupation: "Business owner",
    maritalStatus: "married",
    gender: "female",
    age: 59,
    citizenships: ["GH"],
    joinedDaysAgo: 2210,
    lastContactDaysAgo: 168,
    nextReviewInDays: -84,
    bio: "Long-standing relationship that has gone quiet over the past two quarters.",
    notes:
      "Dormant. No response to three outreach attempts. Attrition risk is elevated.",
    holdings: holdingsFrom(3_100_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 890_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 4_500_000, current: 3_600_000, monthly: 6_000, years: 6, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(26_000),
    expenses: expensesFor(19_000),
    dependents: [],
    targetCashPct: 6,
    heldAwayUsd: 0,
    portfolioDriftPct: 3.4,
    revenueQtdUsd: 6_000,
    netFlowQtdUsd: -420_000,
    performanceYtdPct: 3.6,
    maturingInvestment: null,
  },
  {
    id: "sarpong",
    firstName: "Kojo",
    lastName: "Sarpong",
    email: "kojo.sarpong@example.com",
    phone: "+233 30 248 3311",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Obuasi, Ghana",
    city: "Obuasi",
    country: "Ghana",
    regionCode: "AH",
    residency: "GH resident",
    occupation: "Mining executive",
    maritalStatus: "married",
    gender: "male",
    age: 52,
    citizenships: ["GH"],
    joinedDaysAgo: 1660,
    lastContactDaysAgo: 22,
    nextReviewInDays: 18,
    bio: "Balanced mandate with equity exposure that has run ahead of target.",
    notes: "Equity sleeve is 9 points above the model. Rebalance is due.",
    holdings: holdingsFrom(10_400_000, AGGRESSIVE_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 430_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 11_000_000, current: 6_800_000, monthly: 28_000, years: 11, priority: 1 },
      { title: "Education fund", category: "Education", target: 800_000, current: 540_000, monthly: 6_000, years: 4, priority: 2 },
    ],
    properties: [],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Enterprise Life", name: "Term cover", coverage: 3_000_000, premium: 1_700 },
    ],
    income: incomeFor(58_000),
    expenses: expensesFor(31_000),
    dependents: [{ name: "Ama Sarpong", relationship: "daughter", ageYears: 15 }],
    targetCashPct: 5,
    heldAwayUsd: 800_000,
    portfolioDriftPct: 9.3,
    revenueQtdUsd: 66_000,
    netFlowQtdUsd: 210_000,
    performanceYtdPct: 10.6,
    maturingInvestment: {
      name: "4.9% Corporate Note 2026",
      valueUsd: 600_000,
      maturesInDays: 26,
    },
  },
  {
    id: "mensah-advised",
    firstName: "Kwame",
    lastName: "Mensah",
    email: "kwame.mensah@example.com",
    phone: "+233 24 555 0192",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    regionCode: "AA",
    residency: "GH resident",
    occupation: "Tech founder",
    maritalStatus: "married",
    gender: "male",
    age: 44,
    citizenships: ["GH"],
    joinedDaysAgo: 540,
    lastContactDaysAgo: 6,
    nextReviewInDays: 28,
    assetMandate: "aua",
    bio: "Advisory-only relationship. Portfolio held at external custodians with Fidelity providing planning and allocation guidance.",
    notes: "No Fidelity-managed mandate. Quarterly rebalance guidance only.",
    holdings: [
      {
        name: "Schwab Global Equity ETF",
        symbol: "SCHW",
        assetType: "Equities",
        value: 520_000,
        costBasis: 410_000,
        relationship: "aua",
      },
      {
        name: "Fidelity Bond Ladder",
        symbol: "FID",
        assetType: "Fixed income",
        value: 280_000,
        costBasis: 265_000,
        relationship: "aua",
      },
    ],
    accounts: [
      {
        name: "Brokerage Cash",
        institution: "Charles Schwab",
        type: "current",
        balance: 45_000,
      },
      {
        name: "ISA Cash",
        institution: "Fidelity",
        type: "deposit",
        balance: 55_000,
      },
    ],
    goals: [
      {
        title: "Business exit fund",
        category: "Business",
        target: 1_200_000,
        current: 900_000,
        monthly: 8_000,
        years: 4,
        priority: 1,
      },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(42_000),
    expenses: expensesFor(24_000),
    dependents: [],
    targetCashPct: 8,
    heldAwayUsd: 0,
    portfolioDriftPct: 1.2,
    revenueQtdUsd: 4_200,
    netFlowQtdUsd: 60_000,
    performanceYtdPct: 7.4,
    maturingInvestment: null,
  },
  {
    id: "boateng-advised",
    firstName: "Ama",
    lastName: "Boateng",
    email: "ama.boateng.advised@example.com",
    phone: "+44 7700 900451",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Manchester, UK",
    city: "Manchester",
    country: "United Kingdom",
    residency: "UK resident",
    occupation: "NHS consultant",
    maritalStatus: "single",
    gender: "female",
    age: 39,
    citizenships: ["GB", "GH"],
    joinedDaysAgo: 320,
    lastContactDaysAgo: 19,
    nextReviewInDays: 45,
    assetMandate: "aua",
    bio: "Conservative advisory mandate over assets held entirely at external institutions.",
    notes: "Pension consolidation review scheduled. No discretionary management mandate.",
    holdings: [
      {
        name: "Vanguard LifeStrategy 60",
        symbol: "VLS60",
        assetType: "Equities",
        value: 185_000,
        costBasis: 160_000,
        relationship: "aua",
      },
      {
        name: "UK Gilts ETF",
        symbol: "IGLT",
        assetType: "Fixed income",
        value: 95_000,
        costBasis: 92_000,
        relationship: "aua",
      },
    ],
    accounts: [
      {
        name: "SIPP Cash",
        institution: "Hargreaves Lansdown",
        type: "deposit",
        balance: 70_000,
      },
    ],
    goals: [
      {
        title: "Retirement at 60",
        category: "Retirement",
        target: 800_000,
        current: 350_000,
        monthly: 2_500,
        years: 21,
        priority: 1,
      },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(18_000),
    expenses: expensesFor(11_000),
    dependents: [],
    targetCashPct: 10,
    heldAwayUsd: 0,
    portfolioDriftPct: 0.6,
    revenueQtdUsd: 1_800,
    netFlowQtdUsd: 12_000,
    performanceYtdPct: 4.2,
    maturingInvestment: null,
  },
  {
    id: "asante-advised",
    firstName: "Kofi",
    lastName: "Asante",
    email: "kofi.asante.advised@example.com",
    phone: "+233 20 441 8820",
    status: "active",
    riskLevel: "growth",
    subscription: "free_trial",
    segment: "emerging",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Kumasi, Ghana",
    city: "Kumasi",
    country: "Ghana",
    regionCode: "AH",
    residency: "GH resident",
    occupation: "Software engineer",
    maritalStatus: "single",
    gender: "male",
    age: 31,
    citizenships: ["GH"],
    joinedDaysAgo: 90,
    lastContactDaysAgo: 3,
    nextReviewInDays: 14,
    assetMandate: "aua",
    bio: "Early-career advisory client building wealth through external brokerage accounts.",
    notes: "Trial subscription. Considering managed portfolio migration.",
    holdings: [
      {
        name: "US Tech ETF",
        symbol: "QQQ",
        assetType: "Equities",
        value: 42_000,
        costBasis: 35_000,
        relationship: "aua",
      },
    ],
    accounts: [
      {
        name: "Brokerage",
        institution: "Interactive Brokers",
        type: "current",
        balance: 8_000,
      },
    ],
    goals: [
      {
        title: "First home deposit",
        category: "Property",
        target: 120_000,
        current: 50_000,
        monthly: 1_200,
        years: 5,
        priority: 1,
      },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(9_500),
    expenses: expensesFor(6_200),
    dependents: [],
    targetCashPct: 12,
    heldAwayUsd: 0,
    portfolioDriftPct: 0.4,
    revenueQtdUsd: 450,
    netFlowQtdUsd: 5_000,
    performanceYtdPct: 11.2,
    maturingInvestment: null,
  },
];

/**
 * Additional relationships so the book, analytics and workload views look like
 * a real desk rather than a handful of demo rows.
 */
type FillerSpec = {
  id: string;
  firstName: string;
  lastName: string;
  advisorId: string;
  advisorName: string;
  portfolio: number;
  cash: number;
  riskLevel: ClientSpec["riskLevel"];
  status: ClientSpec["status"];
  segment: ClientSpec["segment"];
  city: string;
  drift: number;
  lastContactDaysAgo: number;
  nextReviewInDays: number;
  heldAway?: number;
};

const FILLERS: FillerSpec[] = [
  { id: "amoah", firstName: "Gifty", lastName: "Amoah", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 5_400_000, cash: 240_000, riskLevel: "moderate", status: "active", segment: "prestige", city: "Accra", drift: 2.1, lastContactDaysAgo: 14, nextReviewInDays: 52 },
  { id: "frimpong", firstName: "Kwesi", lastName: "Frimpong", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 7_900_000, cash: 380_000, riskLevel: "conservative", status: "active", segment: "prestige", city: "Kumasi", drift: 10.4, lastContactDaysAgo: 8, nextReviewInDays: 30 },
  { id: "ofori", firstName: "Adwoa", lastName: "Ofori", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 3_200_000, cash: 620_000, riskLevel: "growth", status: "active", segment: "mass_affluent", city: "Lagos", drift: 4.6, lastContactDaysAgo: 26, nextReviewInDays: 21 },
  { id: "annan", firstName: "Kofi", lastName: "Annan", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 12_600_000, cash: 540_000, riskLevel: "moderate", status: "active", segment: "prestige", city: "Dubai", drift: 3.2, lastContactDaysAgo: 5, nextReviewInDays: 63, heldAway: 1_800_000 },
  { id: "danso", firstName: "Akosua", lastName: "Danso", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 2_100_000, cash: 480_000, riskLevel: "moderate", status: "onboarding", segment: "emerging", city: "New York", drift: 1.1, lastContactDaysAgo: 7, nextReviewInDays: 18 },
  { id: "appiah-r", firstName: "Richard", lastName: "Appiah", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 9_100_000, cash: 1_240_000, riskLevel: "growth", status: "active", segment: "prestige", city: "Toronto", drift: 5.8, lastContactDaysAgo: 12, nextReviewInDays: 9 },
  { id: "yeboah", firstName: "Comfort", lastName: "Yeboah", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 15_300_000, cash: 720_000, riskLevel: "growth", status: "active", segment: "ultra", city: "London", drift: 4.1, lastContactDaysAgo: 18, nextReviewInDays: 37, heldAway: 3_200_000 },
  { id: "bediako", firstName: "Emmanuel", lastName: "Bediako", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 4_600_000, cash: 150_000, riskLevel: "aggressive", status: "active", segment: "mass_affluent", city: "Nairobi", drift: 6.9, lastContactDaysAgo: 33, nextReviewInDays: 25 },
  { id: "acheampong", firstName: "Grace", lastName: "Acheampong", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 6_200_000, cash: 910_000, riskLevel: "moderate", status: "active", segment: "prestige", city: "Sekondi", drift: 2.7, lastContactDaysAgo: 21, nextReviewInDays: 4 },
  { id: "wiredu", firstName: "Samuel", lastName: "Wiredu", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 2_800_000, cash: 90_000, riskLevel: "conservative", status: "inactive", segment: "emerging", city: "Johannesburg", drift: 1.9, lastContactDaysAgo: 142, nextReviewInDays: -60 },
  { id: "obeng", firstName: "Patience", lastName: "Obeng", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 8_400_000, cash: 1_020_000, riskLevel: "growth", status: "active", segment: "prestige", city: "Tamale", drift: 3.6, lastContactDaysAgo: 9, nextReviewInDays: 48 },
  { id: "kyei", firstName: "Daniel", lastName: "Kyei", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 5_900_000, cash: 260_000, riskLevel: "moderate", status: "review", segment: "prestige", city: "Geneva", drift: 4.9, lastContactDaysAgo: 44, nextReviewInDays: -3 },
  { id: "addo", firstName: "Vida", lastName: "Addo", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 3_700_000, cash: 340_000, riskLevel: "moderate", status: "active", segment: "mass_affluent", city: "Bolgatanga", drift: 2.4, lastContactDaysAgo: 16, nextReviewInDays: 55 },
  { id: "gyasi", firstName: "Isaac", lastName: "Gyasi", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 11_800_000, cash: 460_000, riskLevel: "growth", status: "active", segment: "prestige", city: "Accra", drift: 5.1, lastContactDaysAgo: 6, nextReviewInDays: 41, heldAway: 2_400_000 },
  { id: "nyarko", firstName: "Elizabeth", lastName: "Nyarko", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 4_100_000, cash: 780_000, riskLevel: "conservative", status: "active", segment: "mass_affluent", city: "Damongo", drift: 1.6, lastContactDaysAgo: 29, nextReviewInDays: 33 },
  { id: "koomson", firstName: "Ebenezer", lastName: "Koomson", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 7_300_000, cash: 320_000, riskLevel: "moderate", status: "active", segment: "prestige", city: "Tema", drift: 3.9, lastContactDaysAgo: 13, nextReviewInDays: 58 },
  { id: "amponsah", firstName: "Josephine", lastName: "Amponsah", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 2_400_000, cash: 130_000, riskLevel: "growth", status: "onboarding", segment: "emerging", city: "Nalerigu", drift: 0.8, lastContactDaysAgo: 4, nextReviewInDays: 20 },
  { id: "baidoo", firstName: "Michael", lastName: "Baidoo", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 6_700_000, cash: 940_000, riskLevel: "moderate", status: "active", segment: "prestige", city: "Dambai", drift: 2.8, lastContactDaysAgo: 24, nextReviewInDays: 12 },
  { id: "essien", firstName: "Rita", lastName: "Essien", advisorId: "rm-akua", advisorName: "Akua Boateng", portfolio: 9_800_000, cash: 410_000, riskLevel: "growth", status: "active", segment: "prestige", city: "London", drift: 4.3, lastContactDaysAgo: 17, nextReviewInDays: 29, heldAway: 1_100_000 },
  { id: "arthur", firstName: "Prince", lastName: "Arthur", advisorId: "rm-daniel", advisorName: "Daniel Mensah", portfolio: 3_400_000, cash: 200_000, riskLevel: "aggressive", status: "active", segment: "mass_affluent", city: "Winneba", drift: 7.4, lastContactDaysAgo: 38, nextReviewInDays: 16 },
];

/** Onboarding clients waiting in the Assignments inbox. */
const UNASSIGNED_FILLERS: FillerSpec[] = [
  {
    id: "boateng-new",
    firstName: "Yaw",
    lastName: "Boateng",
    advisorId: "",
    advisorName: "Unassigned",
    portfolio: 1_850_000,
    cash: 420_000,
    riskLevel: "moderate",
    status: "onboarding",
    segment: "mass_affluent",
    city: "Accra",
    drift: 0.5,
    lastContactDaysAgo: 2,
    nextReviewInDays: 28,
  },
  {
    id: "sowah-new",
    firstName: "Abena",
    lastName: "Sowah",
    advisorId: "",
    advisorName: "Unassigned",
    portfolio: 4_200_000,
    cash: 680_000,
    riskLevel: "growth",
    status: "onboarding",
    segment: "prestige",
    city: "Kumasi",
    drift: 0.3,
    lastContactDaysAgo: 1,
    nextReviewInDays: 21,
  },
  {
    id: "aidoo-new",
    firstName: "Kwame",
    lastName: "Aidoo",
    advisorId: "",
    advisorName: "Unassigned",
    portfolio: 920_000,
    cash: 180_000,
    riskLevel: "conservative",
    status: "onboarding",
    segment: "emerging",
    city: "Takoradi",
    drift: 0.2,
    lastContactDaysAgo: 4,
    nextReviewInDays: 35,
  },
  {
    id: "mensah-new",
    firstName: "Ama",
    lastName: "Mensah",
    advisorId: "",
    advisorName: "Unassigned",
    portfolio: 6_800_000,
    cash: 1_100_000,
    riskLevel: "moderate",
    status: "onboarding",
    segment: "prestige",
    city: "London",
    drift: 0.6,
    lastContactDaysAgo: 3,
    nextReviewInDays: 14,
    heldAway: 900_000,
  },
  {
    id: "otoo-new",
    firstName: "Kojo",
    lastName: "Otoo",
    advisorId: "",
    advisorName: "Unassigned",
    portfolio: 2_600_000,
    cash: 310_000,
    riskLevel: "growth",
    status: "onboarding",
    segment: "mass_affluent",
    city: "Cape Coast",
    drift: 0.4,
    lastContactDaysAgo: 5,
    nextReviewInDays: 42,
  },
];

const SLEEVES_BY_RISK: Record<
  ClientSpec["riskLevel"],
  typeof GROWTH_SLEEVES
> = {
  conservative: INCOME_SLEEVES,
  moderate: BALANCED_SLEEVES,
  growth: GROWTH_SLEEVES,
  aggressive: AGGRESSIVE_SLEEVES,
};

function fillerToSpec(filler: FillerSpec): ClientSpec {
  const monthlyIncome = Math.round(filler.portfolio * 0.0062);
  const monthlyExpenses = Math.round(monthlyIncome * 0.52);
  const residency = resolveFillerResidency(filler.city);

  return {
    id: filler.id,
    firstName: filler.firstName,
    lastName: filler.lastName,
    email: `${filler.firstName.toLowerCase()}.${filler.lastName.toLowerCase()}@example.com`,
    phone: residency.phone,
    status: filler.status,
    riskLevel: filler.riskLevel,
    subscription: filler.status === "onboarding" ? "free_trial" : "celerey_core",
    segment: filler.segment,
    currency: residency.currency,
    advisorId: filler.advisorId,
    advisorName: filler.advisorName,
    location: residency.location,
    city: residency.city,
    country: residency.country,
    regionCode: residency.regionCode,
    residency: residency.residency,
    occupation: "Private client",
    maritalStatus: "married",
    gender: "female",
    age: 48,
    citizenships: residency.citizenships,
    joinedDaysAgo: 600 + Math.round(filler.portfolio / 20_000),
    lastContactDaysAgo: filler.lastContactDaysAgo,
    nextReviewInDays: filler.nextReviewInDays,
    bio: "Private client relationship managed on the Fidelity advisory platform.",
    notes: "",
    holdings: holdingsFrom(filler.portfolio, SLEEVES_BY_RISK[filler.riskLevel]),
    accounts: [
      {
        name: "Premier Cash Account",
        institution: "Fidelity Bank",
        type: "current",
        balance: filler.cash,
      },
    ],
    goals: [
      {
        title: "Retirement income",
        category: "Retirement",
        target: Math.round(filler.portfolio * 1.5),
        current: Math.round(filler.portfolio * 0.6),
        monthly: Math.round(monthlyIncome * 0.3),
        years: 12,
        priority: 1,
      },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(monthlyIncome),
    expenses: expensesFor(monthlyExpenses),
    dependents: [],
    targetCashPct: 5,
    heldAwayUsd: filler.heldAway ?? 0,
    portfolioDriftPct: filler.drift,
    revenueQtdUsd: Math.round(filler.portfolio * 0.0072),
    netFlowQtdUsd: Math.round(filler.portfolio * 0.02),
    performanceYtdPct: 6 + filler.drift * 0.4,
    maturingInvestment: null,
  };
}

function inferMainSpecMandate(spec: ClientSpec): AssetMandate {
  if (spec.assetMandate) {
    return spec.assetMandate;
  }

  if (spec.id.endsWith("-advised")) {
    return "aua";
  }

  if ((spec.heldAwayUsd ?? 0) > 0) {
    return "mixed";
  }

  if (spec.holdings.some((holding) => holding.relationship === "aua")) {
    return "mixed";
  }

  return "aum";
}

function withAssetMandate(spec: ClientSpec, index: number): ClientSpec {
  const assetMandate =
    spec.assetMandate ??
    (index < SPECS.length
      ? inferMainSpecMandate(spec)
      : defaultAssetMandate(spec, index));

  return { ...spec, assetMandate };
}

export function seedClients(): DemoClientRecord[] {
  const specs = [
    ...SPECS,
    ...REGIONAL_CLIENT_SPECS,
    ...FILLERS.map(fillerToSpec),
    ...UNASSIGNED_FILLERS.map(fillerToSpec),
  ].map(withAssetMandate);

  return specs.map((spec) => buildClientRecord(enrichClientSpec(spec)));
}
