import type { DemoProduct } from "@/lib/demo/types";

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    id: "prd-global-equity-core",
    name: "Global Equity Core Fund",
    provider: "Celerey Asset Management",
    category: "funds",
    summary:
      "Developed-market equity core holding tracking a quality-tilted global index.",
    returnPct: 14.2,
    annualisedPct: 9.8,
    riskBand: "growth",
    feePct: 0.55,
    minimumUsd: 50_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [
      { title: "Fund factsheet", kind: "factsheet" },
      { title: "Key information document", kind: "kid" },
    ],
  },
  {
    id: "prd-em-equity",
    name: "Emerging Markets Equity Fund",
    provider: "Meridian Investors",
    category: "funds",
    summary:
      "Actively managed emerging market equity exposure with an Africa overweight.",
    returnPct: 11.6,
    annualisedPct: 7.4,
    riskBand: "aggressive",
    feePct: 0.95,
    minimumUsd: 100_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: ["Not suitable for conservative mandates"],
    documents: [{ title: "Fund factsheet", kind: "factsheet" }],
  },
  {
    id: "prd-sovereign-ladder",
    name: "Sovereign Bond Ladder",
    provider: "Celerey Asset Management",
    category: "fixed_income",
    summary:
      "Laddered developed-market sovereign bonds from one to seven years for predictable income.",
    returnPct: 4.6,
    annualisedPct: 4.1,
    riskBand: "conservative",
    feePct: 0.2,
    minimumUsd: 250_000,
    liquidity: "weekly",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [{ title: "Mandate summary", kind: "mandate" }],
  },
  {
    id: "prd-ig-credit",
    name: "Investment Grade Credit Fund",
    provider: "Northbridge Capital",
    category: "fixed_income",
    summary: "Diversified investment grade corporate credit with a 4.5 year duration.",
    returnPct: 5.9,
    annualisedPct: 4.8,
    riskBand: "conservative",
    feePct: 0.35,
    minimumUsd: 100_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [{ title: "Fund factsheet", kind: "factsheet" }],
  },
  {
    id: "prd-treasury-plus",
    name: "USD Treasury Plus",
    provider: "Celerey Bank",
    category: "cash",
    summary:
      "Short-dated treasury strategy for cash awaiting deployment, settling in one day.",
    returnPct: 4.9,
    annualisedPct: 4.7,
    riskBand: "conservative",
    feePct: 0.1,
    minimumUsd: 25_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [{ title: "Product summary", kind: "summary" }],
  },
  {
    id: "prd-term-deposit",
    name: "12 Month Term Deposit",
    provider: "Celerey Bank",
    category: "cash",
    summary: "Fixed rate deposit with capital certainty and a defined maturity.",
    returnPct: 5.25,
    annualisedPct: 5.25,
    riskBand: "conservative",
    feePct: 0,
    minimumUsd: 100_000,
    liquidity: "locked",
    currency: "USD",
    available: true,
    restrictions: ["Early withdrawal forfeits accrued interest"],
    documents: [{ title: "Terms and conditions", kind: "terms" }],
  },
  {
    id: "prd-dividend-income",
    name: "Dividend Equity Income",
    provider: "Celerey Asset Management",
    category: "equities",
    summary: "High-quality dividend payers targeting a 3.8% distribution yield.",
    returnPct: 9.4,
    annualisedPct: 8.1,
    riskBand: "moderate",
    feePct: 0.45,
    minimumUsd: 50_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [{ title: "Fund factsheet", kind: "factsheet" }],
  },
  {
    id: "prd-tech-growth",
    name: "Technology Growth Fund",
    provider: "Vertex Partners",
    category: "equities",
    summary: "Concentrated global technology portfolio of 25 to 35 positions.",
    returnPct: 22.8,
    annualisedPct: 15.2,
    riskBand: "aggressive",
    feePct: 1.1,
    minimumUsd: 150_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [
      "Concentration limit of 15% of portfolio",
      "Not suitable for conservative mandates",
    ],
    documents: [{ title: "Fund factsheet", kind: "factsheet" }],
  },
  {
    id: "prd-capital-protected-note",
    name: "Capital Protected Note 2029",
    provider: "Northbridge Capital",
    category: "structured",
    summary:
      "Five year note with 90% capital protection and index participation capped at 45%.",
    returnPct: 7.2,
    annualisedPct: 6.4,
    riskBand: "moderate",
    feePct: 1.2,
    minimumUsd: 250_000,
    liquidity: "locked",
    currency: "USD",
    available: true,
    restrictions: [
      "Requires structured product appropriateness assessment",
      "Not suitable for conservative mandates",
      "Illiquid until maturity",
    ],
    documents: [
      { title: "Term sheet", kind: "termsheet" },
      { title: "Risk disclosure", kind: "disclosure" },
    ],
  },
  {
    id: "prd-autocall-note",
    name: "Autocallable Equity Note",
    provider: "Vertex Partners",
    category: "structured",
    summary:
      "Three year autocallable note on a basket of four global equity indices.",
    returnPct: 9.8,
    annualisedPct: 8.2,
    riskBand: "aggressive",
    feePct: 1.4,
    minimumUsd: 500_000,
    liquidity: "locked",
    currency: "USD",
    available: false,
    restrictions: [
      "Withdrawn pending updated issuer documentation",
      "Requires structured product appropriateness assessment",
    ],
    documents: [{ title: "Term sheet", kind: "termsheet" }],
  },
  {
    id: "prd-absolute-return",
    name: "Absolute Return Fund",
    provider: "Meridian Investors",
    category: "alternatives",
    summary:
      "Multi-strategy hedge allocation targeting cash plus 4% with low equity beta.",
    returnPct: 6.8,
    annualisedPct: 6.1,
    riskBand: "moderate",
    feePct: 1.5,
    minimumUsd: 250_000,
    liquidity: "monthly",
    currency: "USD",
    available: true,
    restrictions: ["Monthly dealing with 15 day notice"],
    documents: [{ title: "Strategy overview", kind: "overview" }],
  },
  {
    id: "prd-gold",
    name: "Physical Gold ETC",
    provider: "Celerey Asset Management",
    category: "alternatives",
    summary: "Fully allocated physical gold holding for portfolio diversification.",
    returnPct: 13.1,
    annualisedPct: 7.9,
    riskBand: "moderate",
    feePct: 0.25,
    minimumUsd: 10_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [],
    documents: [{ title: "Product summary", kind: "summary" }],
  },
  {
    id: "prd-private-equity-vi",
    name: "Private Equity Access Fund VI",
    provider: "Vertex Partners",
    category: "private_markets",
    summary:
      "Diversified private equity feeder with a ten year term and quarterly capital calls.",
    returnPct: 18.4,
    annualisedPct: 14.1,
    riskBand: "aggressive",
    feePct: 1.75,
    minimumUsd: 1_000_000,
    liquidity: "locked",
    currency: "USD",
    available: true,
    restrictions: [
      "Professional clients only",
      "Ten year lock-up",
      "Minimum liquid net worth of $5m",
    ],
    documents: [
      { title: "Private placement memorandum", kind: "ppm" },
      { title: "Subscription agreement", kind: "agreement" },
    ],
  },
  {
    id: "prd-infrastructure",
    name: "African Infrastructure Debt",
    provider: "Meridian Investors",
    category: "private_markets",
    summary:
      "Senior secured infrastructure debt across West African power and transport.",
    returnPct: 10.2,
    annualisedPct: 9.4,
    riskBand: "moderate",
    feePct: 1.2,
    minimumUsd: 500_000,
    liquidity: "quarterly",
    currency: "USD",
    available: true,
    restrictions: ["Professional clients only", "Quarterly redemption windows"],
    documents: [{ title: "Strategy overview", kind: "overview" }],
  },
  {
    id: "prd-lombard",
    name: "Lombard Credit Facility",
    provider: "Celerey Bank",
    category: "lending",
    summary:
      "Revolving credit secured against marketable securities, advancing up to 60% of eligible collateral.",
    returnPct: 0,
    annualisedPct: 0,
    riskBand: "moderate",
    feePct: 0.75,
    minimumUsd: 500_000,
    liquidity: "daily",
    currency: "USD",
    available: true,
    restrictions: [
      "Requires eligible marketable collateral",
      "Subject to margin call on collateral shortfall",
    ],
    documents: [
      { title: "Facility terms", kind: "terms" },
      { title: "Collateral schedule", kind: "schedule" },
    ],
  },
  {
    id: "prd-property-finance",
    name: "Commercial Property Finance",
    provider: "Celerey Bank",
    category: "lending",
    summary:
      "Term finance for income-producing commercial property up to 65% loan to value.",
    returnPct: 0,
    annualisedPct: 0,
    riskBand: "moderate",
    feePct: 1,
    minimumUsd: 1_000_000,
    liquidity: "locked",
    currency: "USD",
    available: true,
    restrictions: ["Independent valuation required", "Credit committee approval"],
    documents: [{ title: "Facility terms", kind: "terms" }],
  },
  {
    id: "prd-whole-of-life",
    name: "Whole of Life Cover",
    provider: "Aegis Global",
    category: "insurance",
    summary:
      "Guaranteed whole of life protection written in trust for estate liquidity.",
    returnPct: 0,
    annualisedPct: 0,
    riskBand: "conservative",
    feePct: 0,
    minimumUsd: 0,
    liquidity: "locked",
    currency: "USD",
    available: true,
    restrictions: ["Medical underwriting required"],
    documents: [{ title: "Policy summary", kind: "summary" }],
  },
  {
    id: "prd-international-health",
    name: "International Health Plan",
    provider: "Bupa",
    category: "insurance",
    summary: "Worldwide private medical cover including evacuation and repatriation.",
    returnPct: 0,
    annualisedPct: 0,
    riskBand: "conservative",
    feePct: 0,
    minimumUsd: 0,
    liquidity: "monthly",
    currency: "USD",
    available: true,
    restrictions: ["Annual renewal with medical history disregarded"],
    documents: [{ title: "Policy summary", kind: "summary" }],
  },
  {
    id: "prd-property-fund",
    name: "Diversified Property Fund",
    provider: "Northbridge Capital",
    category: "alternatives",
    summary:
      "Open-ended commercial property fund across logistics, offices and retail parks.",
    returnPct: 8.4,
    annualisedPct: 6.9,
    riskBand: "moderate",
    feePct: 0.85,
    minimumUsd: 100_000,
    liquidity: "quarterly",
    currency: "USD",
    available: true,
    restrictions: ["Quarterly redemption windows"],
    documents: [{ title: "Fund factsheet", kind: "factsheet" }],
  },
  {
    id: "prd-ghs-treasury",
    name: "GHS Treasury Bill Ladder",
    provider: "Celerey Bank",
    category: "fixed_income",
    summary: "Rolling 91 and 182 day Ghanaian treasury bills held to maturity.",
    returnPct: 21.5,
    annualisedPct: 20.8,
    riskBand: "moderate",
    feePct: 0.15,
    minimumUsd: 20_000,
    liquidity: "monthly",
    currency: "GHS",
    available: true,
    restrictions: ["Local currency exposure", "Withholding tax applies"],
    documents: [{ title: "Product summary", kind: "summary" }],
  },
];

export function productById(id: string): DemoProduct | undefined {
  return DEMO_PRODUCTS.find((product) => product.id === id);
}
