import type { ClientSpec } from "@/lib/demo/seed/client-builder";

/** Showcase client aligned with docs/full-client-by-tab.json (Ada Mensah). */
export const ADA_MENSAH_SPEC: ClientSpec = {
  id: "ada-mensah",
  firstName: "Ada",
  lastName: "Mensah",
  email: "ada.mensah@example.com",
  phone: "+233201234567",
  status: "active",
  riskLevel: "moderate",
  subscription: "celerey_core",
  segment: "affluent",
  currency: "GHS",
  advisorId: "rm-daniel",
  advisorName: "Daniel Mensah",
  location: "Accra, Ghana",
  city: "Accra",
  country: "Ghana",
  regionCode: "AA",
  residency: "solo",
  occupation: "Product Manager",
  maritalStatus: "single",
  gender: "female",
  age: 36,
  citizenships: ["Ghana"],
  joinedDaysAgo: 600,
  lastContactDaysAgo: 4,
  nextReviewInDays: 14,
  bio: "Building toward a home deposit in Accra while growing pension savings.",
  notes: "Strong saver; emergency fund nearly complete.",
  preferredContact: "whatsapp",
  investmentCurrency: "USD",
  prefix: "Ms",
  skipEnrich: true,
  holdings: [
    {
      name: "Apple Inc.",
      symbol: "AAPL",
      assetType: "stock",
      value: 8800,
      costBasis: 6000,
      quantity: 40,
    },
    {
      name: "Bitcoin",
      symbol: "BTC",
      assetType: "crypto",
      value: 22000,
      costBasis: 15000,
      quantity: 0.25,
    },
    {
      name: "Emergency savings",
      assetType: "cash",
      value: 15000,
      costBasis: 15000,
    },
  ],
  accounts: [],
  goals: [
    {
      title: "House deposit",
      category: "housing",
      target: 50000,
      current: 12000,
      monthly: 1370,
      years: 2.3,
      priority: 1,
      targetDate: "2028-12-31",
      icon: "house",
      color: "#3B82F6",
      probability: 88,
    },
    {
      title: "Emergency fund top-up",
      category: "emergency",
      target: 29700,
      current: 15000,
      monthly: 1538,
      years: 0.8,
      priority: 2,
      targetDate: "2027-06-30",
      icon: "shield",
      color: "#EF4444",
      probability: 92,
    },
  ],
  properties: [
    {
      name: "Family home",
      type: "house",
      country: "Ghana",
      city: "Accra",
      purchase: 180000,
      current: 220000,
      purchaseDate: "2022-06-01",
      isPrimary: true,
      mortgage: {
        lender: "GCB",
        balance: 90000,
        interestRatePct: 18,
        minPaymentMonthly: 1800,
        termYears: 20,
        startDate: "2022-06-01",
        originalLoanAmount: 144000,
      },
      insurance: [
        {
          type: "homeowners",
          provider: "Enterprise Insurance",
          policyNumber: "EI-H-99201",
          coverageAmount: 220000,
          annualPremium: 890,
          expiryDate: "2027-06-01",
        },
      ],
    },
  ],
  liabilities: [
    {
      name: "Car loan",
      lender: "Stanbic",
      type: "auto_loan",
      balance: 25000,
      ratePct: 16,
      monthly: 650,
      dueDay: 15,
      originalLoanAmount: 45000,
    },
    {
      name: "Personal loan",
      lender: "Fidelity Bank",
      type: "personal_loan",
      balance: 8000,
      ratePct: 22,
      monthly: 420,
      dueDay: 28,
    },
  ],
  insurance: [
    {
      category: "life",
      provider: "Enterprise Life",
      name: "Term life",
      coverage: 200000,
      premium: 120,
      policyNumber: "EL-TL-442901",
      startDate: "2023-01-01",
      renewalDate: "2027-01-01",
      beneficiary: "Parents",
      notes: "Covers mortgage and family support.",
      autoRenew: true,
    },
    {
      category: "health",
      provider: "NHIS + private top-up",
      name: "Health cover",
      coverage: 50000,
      premium: 85,
      policyNumber: "NHIS-8821",
      startDate: "2024-01-01",
      renewalDate: "2026-12-31",
      autoRenew: true,
    },
  ],
  income: [
    { name: "Salary", amount: 8000, category: "Salary" },
    { name: "Freelance consulting", amount: 1200, category: "Freelance" },
  ],
  expenses: [
    { name: "Rent", amount: 2500, essential: true, category: "Housing" },
    { name: "Groceries", amount: 800, essential: true, category: "Food" },
    { name: "Transport", amount: 400, essential: true, category: "Transport" },
  ],
  dependents: [],
  targetCashPct: 5,
  portfolioDriftPct: 2.1,
  revenueQtdUsd: 4200,
  netFlowQtdUsd: 18000,
  performanceYtdPct: 8.4,
  retirementAge: 60,
  desiredMonthlyIncome: 6000,
  emergencyTargetMonths: 6,
  effectiveTaxRatePct: 22,
  marginalTaxRatePct: 30,
};
