import type { ClientSpec } from "@/lib/demo/seed/client-builder";
import {
  AGGRESSIVE_SLEEVES,
  BALANCED_SLEEVES,
  expensesFor,
  GROWTH_SLEEVES,
  holdingsFrom,
  INCOME_SLEEVES,
  incomeFor,
} from "@/lib/demo/seed/portfolio-helpers";

/**
 * Fully populated Ghana-resident relationships spread across all 16 regions for
 * map, age distribution, and analytics demos.
 */
export const REGIONAL_CLIENT_SPECS: ClientSpec[] = [
  {
    id: "alhassan-tamale",
    firstName: "Fuseini",
    lastName: "Alhassan",
    email: "fuseini.alhassan@example.com",
    phone: "+233 37 209 4400",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Tamale, Ghana",
    city: "Tamale",
    country: "Ghana",
    regionCode: "NP",
    residency: "GH resident",
    occupation: "Agribusiness owner",
    maritalStatus: "married",
    gender: "male",
    age: 54,
    citizenships: ["GH"],
    joinedDaysAgo: 920,
    lastContactDaysAgo: 11,
    nextReviewInDays: 34,
    bio: "Northern region grain aggregation and cold-storage operator diversifying surplus into a balanced portfolio.",
    notes: "Prefers income sleeves. Wants T-bill ladder review before next harvest season.",
    holdings: holdingsFrom(8_200_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 620_000 },
    ],
    goals: [
      { title: "Farm expansion reserve", category: "Business", target: 3_500_000, current: 1_900_000, monthly: 18_000, years: 5, priority: 1 },
      { title: "Retirement income", category: "Retirement", target: 6_000_000, current: 2_800_000, monthly: 12_000, years: 9, priority: 2 },
    ],
    properties: [
      { name: "Tamale warehouse", type: "commercial", country: "Ghana", city: "Tamale", purchase: 1_100_000, current: 1_450_000 },
    ],
    liabilities: [
      { name: "Equipment finance", lender: "GCB Bank", type: "loan", balance: 280_000, ratePct: 14.5, monthly: 9_200 },
    ],
    insurance: [
      { category: "property", provider: "Enterprise Life", name: "Warehouse cover", coverage: 1_500_000, premium: 2_400 },
    ],
    income: incomeFor(72_000),
    expenses: expensesFor(38_000),
    dependents: [{ name: "Amina Alhassan", relationship: "wife", ageYears: 48 }],
    targetCashPct: 8,
    portfolioDriftPct: 2.1,
    revenueQtdUsd: 58_000,
    netFlowQtdUsd: 420_000,
    performanceYtdPct: 5.8,
    maturingInvestment: null,
  },
  {
    id: "dzamesi-ho",
    firstName: "Selorm",
    lastName: "Dzamesi",
    email: "selorm.dzamesi@example.com",
    phone: "+233 36 202 8811",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Ho, Ghana",
    city: "Ho",
    country: "Ghana",
    regionCode: "TV",
    residency: "GH resident",
    occupation: "Manufacturing director",
    maritalStatus: "married",
    gender: "female",
    age: 46,
    citizenships: ["GH"],
    joinedDaysAgo: 540,
    lastContactDaysAgo: 6,
    nextReviewInDays: 28,
    bio: "Volta region textiles executive funding children's international education from a moderate growth mandate.",
    notes: "Education goal is priority. FX exposure review scheduled.",
    holdings: holdingsFrom(5_600_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 310_000 },
    ],
    goals: [
      { title: "International school fees", category: "Education", target: 1_200_000, current: 480_000, monthly: 8_500, years: 3, priority: 1 },
      { title: "Home upgrade", category: "Property", target: 800_000, current: 220_000, monthly: 6_000, years: 4, priority: 2 },
    ],
    properties: [
      { name: "Ho residence", type: "residential", country: "Ghana", city: "Ho", purchase: 420_000, current: 580_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "health", provider: "Bupa", name: "Family health", coverage: 500_000, premium: 1_800 },
    ],
    income: incomeFor(48_000),
    expenses: expensesFor(26_000),
    dependents: [
      { name: "Eli Dzamesi", relationship: "son", ageYears: 12 },
      { name: "Maame Dzamesi", relationship: "daughter", ageYears: 9 },
    ],
    targetCashPct: 6,
    portfolioDriftPct: 3.4,
    revenueQtdUsd: 40_000,
    netFlowQtdUsd: 95_000,
    performanceYtdPct: 7.2,
    maturingInvestment: null,
  },
  {
    id: "ayamba-bolga",
    firstName: "Portia",
    lastName: "Ayamba",
    email: "portia.ayamba@example.com",
    phone: "+233 38 209 3300",
    status: "onboarding",
    riskLevel: "moderate",
    subscription: "free_trial",
    segment: "emerging",
    currency: "GHS",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Bolgatanga, Ghana",
    city: "Bolgatanga",
    country: "Ghana",
    regionCode: "UE",
    residency: "GH resident",
    occupation: "Medical consultant",
    maritalStatus: "single",
    gender: "female",
    age: 34,
    citizenships: ["GH"],
    joinedDaysAgo: 45,
    lastContactDaysAgo: 3,
    nextReviewInDays: 14,
    bio: "Upper East physician building first formal investment plan after locum contracts in Accra.",
    notes: "Onboarding KYC complete. Risk questionnaire pending confirmation call.",
    holdings: holdingsFrom(980_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Savings Account", institution: "Stanbic Bank", type: "savings", balance: 85_000 },
    ],
    goals: [
      { title: "Emergency fund", category: "Safety", target: 120_000, current: 45_000, monthly: 3_500, years: 2, priority: 1 },
      { title: "Clinic setup", category: "Business", target: 600_000, current: 80_000, monthly: 5_000, years: 6, priority: 2 },
    ],
    properties: [],
    liabilities: [
      { name: "Vehicle loan", lender: "CalBank", type: "auto", balance: 32_000, ratePct: 18, monthly: 1_200 },
    ],
    insurance: [
      { category: "health", provider: "NHIS+", name: "Professional indemnity", coverage: 200_000, premium: 450 },
    ],
    income: incomeFor(18_000),
    expenses: expensesFor(9_500),
    dependents: [],
    targetCashPct: 10,
    portfolioDriftPct: 1.2,
    revenueQtdUsd: 7_000,
    netFlowQtdUsd: 40_000,
    performanceYtdPct: 4.1,
    maturingInvestment: null,
  },
  {
    id: "mensah-sunyani",
    firstName: "Kwame",
    lastName: "Mensah-Ba",
    email: "kwame.mensah-ba@example.com",
    phone: "+233 35 249 1100",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Sunyani, Ghana",
    city: "Sunyani",
    country: "Ghana",
    regionCode: "BO",
    residency: "GH resident",
    occupation: "Mining services contractor",
    maritalStatus: "married",
    gender: "male",
    age: 49,
    citizenships: ["GH"],
    joinedDaysAgo: 1100,
    lastContactDaysAgo: 19,
    nextReviewInDays: 42,
    bio: "Brong-Ahafo contractor with held-away business account and cyclical cash flows tied to mining contracts.",
    notes: "Held-away assets need consolidation letter. Cash build-up after Q3 contract payment.",
    holdings: holdingsFrom(11_400_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 890_000 },
      { name: "USD Call Deposit", institution: "Fidelity Bank", type: "deposit", balance: 420_000 },
    ],
    goals: [
      { title: "Contractor retirement", category: "Retirement", target: 14_000_000, current: 7_200_000, monthly: 35_000, years: 10, priority: 1 },
    ],
    properties: [
      { name: "Sunyani office block", type: "commercial", country: "Ghana", city: "Sunyani", purchase: 2_200_000, current: 2_850_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Enterprise Life", name: "Key person cover", coverage: 5_000_000, premium: 3_200 },
    ],
    income: incomeFor(92_000),
    expenses: expensesFor(48_000),
    dependents: [{ name: "Abena Mensah-Ba", relationship: "wife", ageYears: 44 }],
    targetCashPct: 5,
    heldAwayUsd: 2_100_000,
    portfolioDriftPct: 4.8,
    revenueQtdUsd: 82_000,
    netFlowQtdUsd: 680_000,
    performanceYtdPct: 9.4,
    maturingInvestment: null,
  },
  {
    id: "aidoo-takoradi",
    firstName: "Efua",
    lastName: "Aidoo",
    email: "efua.aidoo@example.com",
    phone: "+233 31 229 7700",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Takoradi, Ghana",
    city: "Takoradi",
    country: "Ghana",
    regionCode: "WP",
    residency: "GH resident",
    occupation: "Port logistics CEO",
    maritalStatus: "divorced",
    gender: "female",
    age: 51,
    citizenships: ["GH"],
    joinedDaysAgo: 780,
    lastContactDaysAgo: 8,
    nextReviewInDays: 22,
    bio: "Western region port executive with commercial property exposure and USD-denominated book.",
    notes: "Commercial property revaluation due. Lombard facility renewal in 60 days.",
    holdings: holdingsFrom(14_800_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 540_000 },
    ],
    goals: [
      { title: "Daughter's university", category: "Education", target: 900_000, current: 620_000, monthly: 5_500, years: 2, priority: 1 },
      { title: "Retirement", category: "Retirement", target: 12_000_000, current: 8_100_000, monthly: 22_000, years: 12, priority: 2 },
    ],
    properties: [
      { name: "Harbour view warehouse", type: "commercial", country: "Ghana", city: "Takoradi", purchase: 3_800_000, current: 5_200_000 },
      { name: "Sekondi home", type: "residential", country: "Ghana", city: "Takoradi", purchase: 680_000, current: 920_000 },
    ],
    liabilities: [
      { name: "Warehouse mortgage", lender: "Ecobank", type: "mortgage", balance: 1_400_000, ratePct: 12.5, monthly: 14_800 },
    ],
    insurance: [
      { category: "property", provider: "SIC Insurance", name: "Commercial property", coverage: 5_500_000, premium: 4_100 },
    ],
    income: incomeFor(110_000),
    expenses: expensesFor(52_000),
    dependents: [{ name: "Abena Aidoo", relationship: "daughter", ageYears: 19 }],
    targetCashPct: 4,
    portfolioDriftPct: 3.1,
    revenueQtdUsd: 106_000,
    netFlowQtdUsd: 310_000,
    performanceYtdPct: 8.1,
    maturingInvestment: {
      name: "182-day T-Bill",
      valueUsd: 800_000,
      maturesInDays: 34,
    },
  },
  {
    id: "boateng-koforidua",
    firstName: "Nana",
    lastName: "Boateng",
    email: "nana.boateng@example.com",
    phone: "+233 34 229 5500",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Koforidua, Ghana",
    city: "Koforidua",
    country: "Ghana",
    regionCode: "EP",
    residency: "GH resident",
    occupation: "Diaspora returnee, fintech founder",
    maritalStatus: "married",
    gender: "male",
    age: 38,
    citizenships: ["GH", "US"],
    joinedDaysAgo: 320,
    lastContactDaysAgo: 4,
    nextReviewInDays: 45,
    bio: "Returned from San Francisco to build payments infrastructure; FX-heavy book with dual-currency planning needs.",
    notes: "USD/GHS hedging discussion flagged. Aggressive sleeve within risk band.",
    holdings: holdingsFrom(4_200_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 380_000 },
      { name: "USD Brokerage", institution: "Fidelity Securities", type: "investment", balance: 1_200_000 },
    ],
    goals: [
      { title: "Startup runway", category: "Business", target: 2_000_000, current: 900_000, monthly: 15_000, years: 3, priority: 1 },
      { title: "Accra apartment", category: "Property", target: 600_000, current: 150_000, monthly: 8_000, years: 4, priority: 2 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(55_000),
    expenses: expensesFor(28_000),
    dependents: [{ name: "Esi Boateng", relationship: "wife", ageYears: 35 }],
    targetCashPct: 12,
    heldAwayUsd: 600_000,
    portfolioDriftPct: 5.6,
    revenueQtdUsd: 30_000,
    netFlowQtdUsd: 180_000,
    performanceYtdPct: 11.2,
    maturingInvestment: null,
  },
  {
    id: "awuah-wa",
    firstName: "Dominic",
    lastName: "Awuah",
    email: "dominic.awuah@example.com",
    phone: "+233 39 209 2200",
    status: "review",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Wa, Ghana",
    city: "Wa",
    country: "Ghana",
    regionCode: "UW",
    residency: "GH resident",
    occupation: "NGO programme director",
    maritalStatus: "married",
    gender: "male",
    age: 43,
    citizenships: ["GH"],
    joinedDaysAgo: 650,
    lastContactDaysAgo: 31,
    nextReviewInDays: -5,
    bio: "Upper West NGO leader with conservative mandate and overdue annual review.",
    notes: "Review overdue. Client travelling — schedule virtual check-in.",
    holdings: holdingsFrom(2_800_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 195_000 },
    ],
    goals: [
      { title: "Children's education", category: "Education", target: 400_000, current: 180_000, monthly: 4_000, years: 6, priority: 1 },
    ],
    properties: [
      { name: "Wa family home", type: "residential", country: "Ghana", city: "Wa", purchase: 180_000, current: 240_000 },
    ],
    liabilities: [],
    insurance: [],
    income: incomeFor(32_000),
    expenses: expensesFor(17_000),
    dependents: [
      { name: "Kofi Awuah", relationship: "son", ageYears: 10 },
      { name: "Ama Awuah", relationship: "daughter", ageYears: 7 },
    ],
    targetCashPct: 7,
    portfolioDriftPct: 1.8,
    revenueQtdUsd: 20_000,
    netFlowQtdUsd: 55_000,
    performanceYtdPct: 4.6,
    maturingInvestment: null,
  },
  {
    id: "otabil-madina",
    firstName: "Linda",
    lastName: "Otabil",
    email: "linda.otabil@example.com",
    phone: "+233 30 281 9900",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "ultra",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Madina, Ghana",
    city: "Madina",
    country: "Ghana",
    regionCode: "AA",
    residency: "GH resident",
    occupation: "Telecoms executive",
    maritalStatus: "married",
    gender: "female",
    age: 44,
    citizenships: ["GH"],
    joinedDaysAgo: 1400,
    lastContactDaysAgo: 7,
    nextReviewInDays: 56,
    bio: "Greater Accra telecoms SVP with significant equity compensation and philanthropy goals.",
    notes: "RSU vesting in Q4. Philanthropy fund discussion ongoing.",
    holdings: holdingsFrom(22_500_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 1_800_000 },
    ],
    goals: [
      { title: "Foundation endowment", category: "Philanthropy", target: 8_000_000, current: 3_200_000, monthly: 45_000, years: 7, priority: 1 },
      { title: "Retirement", category: "Retirement", target: 18_000_000, current: 12_400_000, monthly: 40_000, years: 15, priority: 2 },
    ],
    properties: [
      { name: "Madina residence", type: "residential", country: "Ghana", city: "Madina", purchase: 1_600_000, current: 2_100_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Aegis Global", name: "Executive cover", coverage: 8_000_000, premium: 5_400 },
    ],
    income: incomeFor(165_000),
    expenses: expensesFor(72_000),
    dependents: [{ name: "Joel Otabil", relationship: "son", ageYears: 16 }],
    targetCashPct: 4,
    heldAwayUsd: 1_500_000,
    portfolioDriftPct: 4.2,
    revenueQtdUsd: 162_000,
    netFlowQtdUsd: 1_100_000,
    performanceYtdPct: 10.8,
    maturingInvestment: null,
    effectiveTaxRatePct: 28,
    marginalTaxRatePct: 35,
  },
  {
    id: "asante-obuasi",
    firstName: "Yaw",
    lastName: "Asante",
    email: "yaw.asante@example.com",
    phone: "+233 32 249 6600",
    status: "active",
    riskLevel: "aggressive",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Obuasi, Ghana",
    city: "Obuasi",
    country: "Ghana",
    regionCode: "AH",
    residency: "GH resident",
    occupation: "Mining engineer",
    maritalStatus: "single",
    gender: "male",
    age: 36,
    citizenships: ["GH"],
    joinedDaysAgo: 280,
    lastContactDaysAgo: 10,
    nextReviewInDays: 38,
    bio: "Ashanti region mining engineer with aggressive growth preference and high savings rate.",
    notes: "Drift above band. Discuss rebalancing vs tax implications.",
    holdings: holdingsFrom(6_800_000, AGGRESSIVE_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 120_000 },
    ],
    goals: [
      { title: "Early retirement", category: "Retirement", target: 8_000_000, current: 3_400_000, monthly: 18_000, years: 14, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(78_000),
    expenses: expensesFor(35_000),
    dependents: [],
    targetCashPct: 3,
    portfolioDriftPct: 8.2,
    revenueQtdUsd: 49_000,
    netFlowQtdUsd: 240_000,
    performanceYtdPct: 14.1,
    maturingInvestment: null,
  },
  {
    id: "quarshie-cape-coast",
    firstName: "Henrietta",
    lastName: "Quarshie",
    email: "henrietta.quarshie@example.com",
    phone: "+233 33 213 4400",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Cape Coast, Ghana",
    city: "Cape Coast",
    country: "Ghana",
    regionCode: "CP",
    residency: "GH resident",
    occupation: "University administrator",
    maritalStatus: "widowed",
    gender: "female",
    age: 61,
    citizenships: ["GH"],
    joinedDaysAgo: 890,
    lastContactDaysAgo: 15,
    nextReviewInDays: 19,
    bio: "Central region academic approaching retirement with income-focused allocation.",
    notes: "Decumulation planning conversation needed within 12 months.",
    holdings: holdingsFrom(3_600_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 280_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 4_500_000, current: 3_600_000, monthly: 2_000, years: 4, priority: 1 },
    ],
    properties: [
      { name: "Cape Coast home", type: "residential", country: "Ghana", city: "Cape Coast", purchase: 320_000, current: 410_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "health", provider: "NHIS+", name: "Supplemental health", coverage: 150_000, premium: 680 },
    ],
    income: incomeFor(28_000),
    expenses: expensesFor(14_000),
    dependents: [],
    targetCashPct: 8,
    portfolioDriftPct: 2.3,
    revenueQtdUsd: 26_000,
    netFlowQtdUsd: 40_000,
    performanceYtdPct: 5.2,
    retirementAge: 65,
    desiredMonthlyIncome: 12_000,
    maturingInvestment: null,
  },
  {
    id: "nortey-tema",
    firstName: "Edem",
    lastName: "Nortey",
    email: "edem.nortey@example.com",
    phone: "+233 30 300 7700",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Tema, Ghana",
    city: "Tema",
    country: "Ghana",
    regionCode: "AA",
    residency: "GH resident",
    occupation: "Shipping agent",
    maritalStatus: "married",
    gender: "male",
    age: 47,
    citizenships: ["GH"],
    joinedDaysAgo: 720,
    lastContactDaysAgo: 12,
    nextReviewInDays: 33,
    bio: "Tema port shipping agent with cyclical bonuses and moderate balanced mandate.",
    notes: "Bonus received last month — deploy cash per IPS.",
    holdings: holdingsFrom(9_300_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 720_000 },
    ],
    goals: [
      { title: "Boat acquisition", category: "Lifestyle", target: 1_500_000, current: 400_000, monthly: 10_000, years: 5, priority: 2 },
      { title: "Retirement", category: "Retirement", target: 10_000_000, current: 5_800_000, monthly: 20_000, years: 12, priority: 1 },
    ],
    properties: [
      { name: "Tema harbour apartment", type: "residential", country: "Ghana", city: "Tema", purchase: 520_000, current: 690_000 },
    ],
    liabilities: [],
    insurance: [],
    income: incomeFor(68_000),
    expenses: expensesFor(36_000),
    dependents: [
      { name: "Elorm Nortey", relationship: "son", ageYears: 14 },
      { name: "Mawuli Nortey", relationship: "daughter", ageYears: 11 },
    ],
    targetCashPct: 6,
    portfolioDriftPct: 3.7,
    revenueQtdUsd: 67_000,
    netFlowQtdUsd: 290_000,
    performanceYtdPct: 7.8,
    maturingInvestment: null,
  },
  {
    id: "ampofo-accra",
    firstName: "Abena",
    lastName: "Ampofo",
    email: "abena.ampofo@example.com",
    phone: "+233 30 277 8800",
    status: "inactive",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "emerging",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Winneba, Ghana",
    city: "Winneba",
    country: "Ghana",
    regionCode: "CP",
    residency: "GH resident",
    occupation: "Retail entrepreneur",
    maritalStatus: "separated",
    gender: "female",
    age: 52,
    citizenships: ["GH"],
    joinedDaysAgo: 1200,
    lastContactDaysAgo: 120,
    nextReviewInDays: -45,
    bio: "Former active client; business slowdown led to reduced engagement.",
    notes: "Re-engagement outreach planned. Portfolio in preservation mode.",
    holdings: holdingsFrom(1_400_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 180_000 },
    ],
    goals: [],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(15_000),
    expenses: expensesFor(12_000),
    dependents: [],
    targetCashPct: 15,
    portfolioDriftPct: 0.9,
    revenueQtdUsd: 10_000,
    netFlowQtdUsd: -20_000,
    performanceYtdPct: 3.1,
    maturingInvestment: null,
  },
  {
    id: "adutwum-kumasi",
    firstName: "George",
    lastName: "Adutwum",
    email: "george.adutwum@example.com",
    phone: "+233 32 204 9900",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "ultra",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Kumasi, Ghana",
    city: "Kumasi",
    country: "Ghana",
    regionCode: "AH",
    residency: "GH resident",
    occupation: "Cocoa processing magnate",
    maritalStatus: "married",
    gender: "male",
    age: 62,
    citizenships: ["GH"],
    joinedDaysAgo: 2100,
    lastContactDaysAgo: 5,
    nextReviewInDays: 60,
    bio: "Ashanti cocoa processing family office with multi-generational wealth transfer planning.",
    notes: "Estate planning attorney intro pending. Succession workshop scheduled.",
    holdings: holdingsFrom(28_000_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 2_100_000 },
      { name: "Family trust account", institution: "Fidelity Trust", type: "trust", balance: 8_500_000 },
    ],
    goals: [
      { title: "Family trust funding", category: "Legacy", target: 20_000_000, current: 14_000_000, monthly: 50_000, years: 8, priority: 1 },
      { title: "Grandchildren education", category: "Education", target: 3_000_000, current: 1_800_000, monthly: 12_000, years: 10, priority: 2 },
    ],
    properties: [
      { name: "Kumasi estate", type: "residential", country: "Ghana", city: "Kumasi", purchase: 2_400_000, current: 3_600_000 },
      { name: "Processing plant", type: "commercial", country: "Ghana", city: "Kumasi", purchase: 6_000_000, current: 8_200_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Aegis Global", name: "Family office cover", coverage: 15_000_000, premium: 9_800 },
    ],
    income: incomeFor(220_000),
    expenses: expensesFor(95_000),
    dependents: [
      { name: "Kwesi Adutwum", relationship: "son", ageYears: 32 },
      { name: "Akosua Adutwum", relationship: "daughter", ageYears: 28 },
    ],
    targetCashPct: 5,
    heldAwayUsd: 4_200_000,
    portfolioDriftPct: 2.8,
    revenueQtdUsd: 201_000,
    netFlowQtdUsd: 890_000,
    performanceYtdPct: 7.5,
    maturingInvestment: null,
    effectiveTaxRatePct: 32,
    marginalTaxRatePct: 38,
  },
  {
    id: "tetteh-accra",
    firstName: "Maame",
    lastName: "Tetteh-Quaye",
    email: "maame.tetteh@example.com",
    phone: "+233 30 255 4400",
    status: "onboarding",
    riskLevel: "growth",
    subscription: "free_trial",
    segment: "emerging",
    currency: "GHS",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    regionCode: "AA",
    residency: "GH resident",
    occupation: "Software engineer",
    maritalStatus: "single",
    gender: "female",
    age: 28,
    citizenships: ["GH"],
    joinedDaysAgo: 21,
    lastContactDaysAgo: 2,
    nextReviewInDays: 30,
    bio: "Young Accra tech professional starting first structured investment plan after ESOP liquidity event.",
    notes: "Risk profile confirmed as growth. First advisory session booked.",
    holdings: holdingsFrom(650_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Savings Account", institution: "Fidelity Bank", type: "savings", balance: 45_000 },
    ],
    goals: [
      { title: "First home deposit", category: "Property", target: 200_000, current: 60_000, monthly: 4_500, years: 3, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(22_000),
    expenses: expensesFor(11_000),
    dependents: [],
    targetCashPct: 10,
    portfolioDriftPct: 0.5,
    revenueQtdUsd: 4_700,
    netFlowQtdUsd: 120_000,
    performanceYtdPct: 8.9,
    maturingInvestment: null,
  },
  {
    id: "agyeman-accra",
    firstName: "Kweku",
    lastName: "Agyeman",
    email: "kweku.agyeman@example.com",
    phone: "+233 30 299 1100",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Accra, Ghana",
    city: "Accra",
    country: "Ghana",
    regionCode: "AA",
    residency: "GH resident",
    occupation: "Private equity partner",
    maritalStatus: "married",
    gender: "male",
    age: 41,
    citizenships: ["GH", "GB"],
    joinedDaysAgo: 480,
    lastContactDaysAgo: 9,
    nextReviewInDays: 41,
    bio: "Accra-based PE partner with illiquid co-investments and regular capital calls.",
    notes: "Capital call due in 45 days. Maintain elevated cash buffer.",
    holdings: holdingsFrom(16_200_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 1_400_000 },
    ],
    goals: [
      { title: "Co-invest reserve", category: "Investment", target: 5_000_000, current: 2_800_000, monthly: 25_000, years: 4, priority: 1 },
      { title: "Retirement", category: "Retirement", target: 15_000_000, current: 8_900_000, monthly: 30_000, years: 18, priority: 2 },
    ],
    properties: [
      { name: "East Legon home", type: "residential", country: "Ghana", city: "Accra", purchase: 1_100_000, current: 1_550_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "life", provider: "Aegis Global", name: "Term cover", coverage: 4_000_000, premium: 2_900 },
    ],
    income: incomeFor(130_000),
    expenses: expensesFor(58_000),
    dependents: [
      { name: "Adjoa Agyeman", relationship: "wife", ageYears: 38 },
      { name: "Kofi Agyeman", relationship: "son", ageYears: 6 },
    ],
    targetCashPct: 9,
    heldAwayUsd: 3_800_000,
    portfolioDriftPct: 4.5,
    revenueQtdUsd: 116_000,
    netFlowQtdUsd: 520_000,
    performanceYtdPct: 10.2,
    maturingInvestment: {
      name: "91-day T-Bill",
      valueUsd: 500_000,
      maturesInDays: 18,
    },
  },
  {
    id: "adu-techiman",
    firstName: "Ama",
    lastName: "Adu-Gyamfi",
    email: "ama.adu@example.com",
    phone: "+233 35 259 4400",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Techiman, Ghana",
    city: "Techiman",
    country: "Ghana",
    regionCode: "BE",
    residency: "GH resident",
    occupation: "Yam and maize trader",
    maritalStatus: "married",
    gender: "female",
    age: 42,
    citizenships: ["GH"],
    joinedDaysAgo: 410,
    lastContactDaysAgo: 14,
    nextReviewInDays: 36,
    bio: "Bono East market trader formalising seasonal surpluses into a balanced portfolio.",
    notes: "Prefers quarterly reviews after harvest cycles.",
    holdings: holdingsFrom(3_100_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 210_000 },
    ],
    goals: [
      { title: "Trading capital reserve", category: "Business", target: 1_800_000, current: 900_000, monthly: 8_000, years: 4, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(34_000),
    expenses: expensesFor(18_000),
    dependents: [{ name: "Kwame Adu-Gyamfi", relationship: "husband", ageYears: 45 }],
    targetCashPct: 9,
    portfolioDriftPct: 2.4,
    revenueQtdUsd: 22_000,
    netFlowQtdUsd: 85_000,
    performanceYtdPct: 6.3,
    maturingInvestment: null,
  },
  {
    id: "osei-goaso",
    firstName: "Robert",
    lastName: "Osei",
    email: "robert.osei@example.com",
    phone: "+233 35 269 1100",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Goaso, Ghana",
    city: "Goaso",
    country: "Ghana",
    regionCode: "AF",
    residency: "GH resident",
    occupation: "Hospital administrator",
    maritalStatus: "married",
    gender: "male",
    age: 50,
    citizenships: ["GH"],
    joinedDaysAgo: 680,
    lastContactDaysAgo: 20,
    nextReviewInDays: 44,
    bio: "Ahafo region healthcare administrator building retirement income from a conservative mandate.",
    notes: "Income sleeve preference. Review T-bill ladder annually.",
    holdings: holdingsFrom(2_400_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 165_000 },
    ],
    goals: [
      { title: "Retirement income", category: "Retirement", target: 3_500_000, current: 2_100_000, monthly: 6_500, years: 10, priority: 1 },
    ],
    properties: [
      { name: "Goaso residence", type: "residential", country: "Ghana", city: "Goaso", purchase: 210_000, current: 285_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "health", provider: "NHIS+", name: "Family cover", coverage: 180_000, premium: 520 },
    ],
    income: incomeFor(26_000),
    expenses: expensesFor(14_000),
    dependents: [],
    targetCashPct: 8,
    portfolioDriftPct: 1.5,
    revenueQtdUsd: 18_000,
    netFlowQtdUsd: 42_000,
    performanceYtdPct: 4.8,
    maturingInvestment: null,
  },
  {
    id: "kumi-bibiani",
    firstName: "Theresa",
    lastName: "Kumi",
    email: "theresa.kumi@example.com",
    phone: "+233 35 279 8800",
    status: "active",
    riskLevel: "moderate",
    subscription: "celerey_core",
    segment: "prestige",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Bibiani, Ghana",
    city: "Bibiani",
    country: "Ghana",
    regionCode: "WN",
    residency: "GH resident",
    occupation: "Forestry concession holder",
    maritalStatus: "widowed",
    gender: "female",
    age: 57,
    citizenships: ["GH"],
    joinedDaysAgo: 1050,
    lastContactDaysAgo: 17,
    nextReviewInDays: 52,
    bio: "Western North timber and cocoa landowner diversifying illiquid holdings into marketable assets.",
    notes: "Property valuation update requested for collateral discussion.",
    holdings: holdingsFrom(5_500_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 340_000 },
    ],
    goals: [
      { title: "Land succession plan", category: "Legacy", target: 4_000_000, current: 2_200_000, monthly: 10_000, years: 8, priority: 1 },
    ],
    properties: [
      { name: "Bibiani cocoa farm", type: "commercial", country: "Ghana", city: "Bibiani", purchase: 890_000, current: 1_150_000 },
    ],
    liabilities: [],
    insurance: [
      { category: "property", provider: "SIC Insurance", name: "Farm cover", coverage: 1_200_000, premium: 1_600 },
    ],
    income: incomeFor(44_000),
    expenses: expensesFor(22_000),
    dependents: [],
    targetCashPct: 6,
    portfolioDriftPct: 3.2,
    revenueQtdUsd: 36_000,
    netFlowQtdUsd: 110_000,
    performanceYtdPct: 6.9,
    maturingInvestment: null,
  },
  {
    id: "agbeko-dambai",
    firstName: "Jonathan",
    lastName: "Agbeko",
    email: "jonathan.agbeko@example.com",
    phone: "+233 36 219 3300",
    status: "active",
    riskLevel: "growth",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Dambai, Ghana",
    city: "Dambai",
    country: "Ghana",
    regionCode: "OT",
    residency: "GH resident",
    occupation: "Education NGO director",
    maritalStatus: "married",
    gender: "male",
    age: 39,
    citizenships: ["GH"],
    joinedDaysAgo: 290,
    lastContactDaysAgo: 8,
    nextReviewInDays: 40,
    bio: "Oti region NGO lead building a growth portfolio from grant management fees and consulting income.",
    notes: "Wants ESG-aligned fund options within growth sleeve.",
    holdings: holdingsFrom(2_900_000, GROWTH_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 175_000 },
    ],
    goals: [
      { title: "School building fund", category: "Philanthropy", target: 800_000, current: 320_000, monthly: 5_500, years: 5, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(31_000),
    expenses: expensesFor(16_000),
    dependents: [{ name: "Grace Agbeko", relationship: "wife", ageYears: 36 }],
    targetCashPct: 7,
    portfolioDriftPct: 4.1,
    revenueQtdUsd: 19_000,
    netFlowQtdUsd: 65_000,
    performanceYtdPct: 9.1,
    maturingInvestment: null,
  },
  {
    id: "andoh-damongo",
    firstName: "Felicia",
    lastName: "Andoh",
    email: "felicia.andoh@example.com",
    phone: "+233 37 219 5500",
    status: "active",
    riskLevel: "conservative",
    subscription: "celerey_core",
    segment: "mass_affluent",
    currency: "USD",
    advisorId: "rm-daniel",
    advisorName: "Daniel Mensah",
    location: "Damongo, Ghana",
    city: "Damongo",
    country: "Ghana",
    regionCode: "SV",
    residency: "GH resident",
    occupation: "Shea butter cooperative chair",
    maritalStatus: "married",
    gender: "female",
    age: 48,
    citizenships: ["GH"],
    joinedDaysAgo: 520,
    lastContactDaysAgo: 13,
    nextReviewInDays: 47,
    bio: "Savannah region cooperative leader preserving capital while funding warehouse expansion.",
    notes: "Conservative mandate. Discuss microfinance exposure limits.",
    holdings: holdingsFrom(1_850_000, INCOME_SLEEVES),
    accounts: [
      { name: "Premier Cash Account", institution: "Fidelity Bank", type: "current", balance: 140_000 },
    ],
    goals: [
      { title: "Cooperative warehouse", category: "Business", target: 600_000, current: 280_000, monthly: 4_200, years: 4, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(22_000),
    expenses: expensesFor(12_000),
    dependents: [],
    targetCashPct: 10,
    portfolioDriftPct: 1.1,
    revenueQtdUsd: 14_000,
    netFlowQtdUsd: 38_000,
    performanceYtdPct: 4.2,
    maturingInvestment: null,
  },
  {
    id: "bukari-nalerigu",
    firstName: "Ibrahim",
    lastName: "Bukari",
    email: "ibrahim.bukari@example.com",
    phone: "+233 38 219 6600",
    status: "onboarding",
    riskLevel: "moderate",
    subscription: "free_trial",
    segment: "emerging",
    currency: "GHS",
    advisorId: "rm-akua",
    advisorName: "Akua Boateng",
    location: "Nalerigu, Ghana",
    city: "Nalerigu",
    country: "Ghana",
    regionCode: "NE",
    residency: "GH resident",
    occupation: "Livestock trader",
    maritalStatus: "married",
    gender: "male",
    age: 33,
    citizenships: ["GH"],
    joinedDaysAgo: 38,
    lastContactDaysAgo: 5,
    nextReviewInDays: 21,
    bio: "North East cattle trader onboarding after a profitable export season.",
    notes: "KYC in progress. Initial funding from mobile money sweep.",
    holdings: holdingsFrom(720_000, BALANCED_SLEEVES),
    accounts: [
      { name: "Savings Account", institution: "GCB Bank", type: "savings", balance: 55_000 },
    ],
    goals: [
      { title: "Working capital buffer", category: "Business", target: 250_000, current: 90_000, monthly: 3_000, years: 2, priority: 1 },
    ],
    properties: [],
    liabilities: [],
    insurance: [],
    income: incomeFor(14_000),
    expenses: expensesFor(8_000),
    dependents: [{ name: "Rahinatu Bukari", relationship: "wife", ageYears: 29 }],
    targetCashPct: 12,
    portfolioDriftPct: 0.6,
    revenueQtdUsd: 5_500,
    netFlowQtdUsd: 28_000,
    performanceYtdPct: 5.4,
    maturingInvestment: null,
  },
];
